#' Downloads all the satellite images and lighting images from the Hong Kong Observatory. If there is a Chinese and English version, only downloads the English version.
#'
#' @return
#' @export
#'
#' @examples HKOall()
HKOall = function(){
  message("...Downloading all available HKO data...")
  message("")
  message("Lighting --- 064km, Cloud-to-Cloud")
  HKOlighting(range = 64, type = "CC")
  message("")
  message("Lighting --- 064km, Cloud-to-Ground")
  HKOlighting(range = 64, type = "CG")
  message("")
  message("Lighting --- 256km, Cloud-to-Cloud")
  HKOlighting(range = 256, type = "CC")
  message("")
  message("Lighting --- 256km, Cloud-to-Ground")
  HKOlighting(range = 256, type = "CG")
  message("")
  message("Satellite --- 8 times, True-Color")
  HKOsatellite(magn = 8, type = "tc", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Satellite --- 4 times, True-Color")
  HKOsatellite(magn = 4, type = "tc", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Satellite --- 2 times, True-Color")
  HKOsatellite(magn = 2, type = "tc", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Satellite --- 8 times, Infra-Red")
  HKOsatellite(magn = 8, type = "ir", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Satellite --- 4 times, Infra-Red")
  HKOsatellite(magn = 4, type = "ir", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Satellite --- 2 times, Infra-Red")
  HKOsatellite(magn = 2, type = "ir", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Satellite --- 8 times, Deep-Convection")
  HKOsatellite(magn = 8, type = "dc", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Satellite --- 4 times, Deep-Convection")
  HKOsatellite(magn = 4, type = "dc", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Satellite --- 2 times, Deep-Convection")
  HKOsatellite(magn = 2, type = "dc", DDays = 3.5, DTime = Sys.time(), listfail = F)
  message("")
  message("Wind --- English")
  HKOwind(type = "wind", lan = "e")
  message("")
  message("Gust --- English")
  HKOwind(type = "gust", lan = "e")
  message("")
  message("Hourly Rainfall --- English")
  HKOrfhr(lan = "e")
  message("")
  message("5 minute tidal height --- English")
  HKOtide(lan = "e")
  message("")
  message("-----------Download completed-----------")
}
